=== siiftun1857/workspace/employees.dtd
<!ELEMENT employees (employee*)>
<!ELEMENT employee (name,sex,age)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ATTLIST employee tag CDATA #IMPLIED>

=== siiftun1857/workspace/TestDom4/employees.xml
<?xml version="1.0" encoding="GBK"?>
<!DOCTYPE employees SYSTEM "https://raw.githubusercontent.com/siiftun1857/Webs1/master/employees.dtd">
<employees>
	<employee tag="1">
		<name>Mike Magnus</name>
		<sex>Male</sex>
		<age>31</age>
	</employee>
	<employee tag="2">
		<name>Mei</name>
		<sex>Female</sex>
		<age>31</age>
	</employee>
	<employee tag="3">
		<name>Frank Alice</name>
		<sex>Female</sex>
		<age>23</age>
	</employee>
</employees>
